### ISSUE TITLE
Keyboard type issue

### ISSUE THREAD

**Issue by AmandusHD** [cry0h/Teensyterpreter#4]
Because i'm from noway we got a different kind of keyboard with 3 extra letters æøå

when i try to execute the script i could use the example when it opens up cmd, the right code should be cmd.exe /T:01 /K mode CON: COLS=15 LINES=1

but it would output: cmd -Q -D -TØ7F -FØOFF -VØON -K DELAY 500

it is the same problem with the rest of the script as well. 
the cmd thing was just the example

**Comment by Clamb94** [comment]
I've noticed the same problem with a german keyboard. Switching the keyboad to english seems to be working

**Comment by AmandusHD** [comment]
Didn't work for me tho =/

**Comment by KernelEquinox** [comment]
Sorry about the delay.

I created the code on a QWERTY keyboard in the English locale, so the actual key presses might result in different letters being typed based on the locale. Does changing your system's locale to English still produce the issue?

**Comment by Clamb94** [comment]
I think I found a solution. Before uploading the code, you can select the Keyboard layout in the Arduino IDE under tools -> keyboard layout. After selecting the correct layout, in my case German, everything worked fine.
