### ISSUE TITLE
Powershell stops responding.

### ISSUE THREAD

**Issue by fionafibration** [cry0h/Teensyterpreter#9]
Says there is a win32 exception. I am testing on windows 7 with a 64 bit operating system. The output of the program into notepad is attached.
[output.txt](https://github.com/KernelEquinox/Teensyterpreter/files/421454/output.txt)
When the text file is opened in visual studio and ran, the following error occurs:
`PS C:\Users\CTCPublic\Documents> C:\Users\CTCPublic\Documents\output.ps1
Missing '(' after 'if' in if statement.
At C:\Users\CTCPublic\Documents\output.ps1:1 char:4
- if  <<<< exist C:\Windows\SysWOW64 ( set PWRSHLXDD=C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell) else ( set PWRSHLXDD=powershell )
  - CategoryInfo          : ParserError: (OpenParenToken:TokenId) [], ParentContainsErrorRecordException
  - FullyQualifiedErrorId : MissingEndParenthesisInIfStatement`

**Comment by fionafibration** [comment]
Thank you, I hope this issue is fixed soon as I want to start hacking with my teensy soon.

**Comment by fionafibration** [comment]
Nevermind. It was a problem with github's copy and paste.

**Comment by fionafibration** [comment]
Thanks.

**Comment by KernelEquinox** [comment]
Oh jeez, sorry for the late reply; glad to see you got it working though!
